# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0002_auto_20180323_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
