# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0003_auto_20180327_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
