# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0006_auto_20180420_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
