# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0007_auto_20180420_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
