# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0011_auto_20180430_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_buyed',
            field=models.BooleanField(default=False),
        ),
    ]
