# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0012_product_is_buyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='adress',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
