# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0013_bill_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
