# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0016_auto_20180514_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenda.Product'),
        ),
    ]
