# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import tenda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0017_auto_20180514_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=tenda.models.get_image_path, verbose_name='Image'),
        ),
    ]
