# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0018_auto_20180605_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'get_latest_by': ['data']},
        ),
    ]
