# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenda', '0021_auto_20180605_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['data']},
        ),
    ]
